### ISSUE TITLE
Nem jelenik meg a videó

### ISSUE THREAD

**Issue by virag004** [MicrosoftDocs/azure-docs.hu-hu#40]
Csak üres tér van a videó helyén

---
#### A dokumentum adatai

⚠ *Ezt a szakaszt ne szerkessze. A szakasz a docs.microsoft.com ➟ GitHub-problémák hivatkozásaihoz szükséges.*

* ID: 1534d9c1-c568-f744-7cec-07f107333a3a
* Version Independent ID: 0c56ac88-b762-38a3-6b1c-d086597f0c5a
* Content: [Azure Cosmos DB: Hogyan végezhető lekérdezés a MongoDB API használatával?](https://docs.microsoft.com/hu-hu/azure/cosmos-db/tutorial-query-mongodb)
* Content Source: [articles/cosmos-db/tutorial-query-mongodb.md](https://github.com/MicrosoftDocs/azure-docs.hu-hu/blob/live/articles/cosmos-db/tutorial-query-mongodb.md)
* Service: **cosmos-db**
* GitHub Login: @SnehaGunda
* Microsoft Alias: **sngun**

**Comment by LisandroSu** [comment]
Issue moved to [MicrosoftDocs/azure-docs #12375](https://github.com/MicrosoftDocs/azure-docs/issues/12375) via [**ZenHub**](https://www.zenhub.com/)

**Comment by LisandroSu** [comment]
Üdvözöljük,   @virag004 !


Köszönjük értékes   hozzájárulását. Visszajelzése az eredeti dokumentumhoz kapcsolódik.
 
Ezért ezt a problémát az angol   nyelvű adattárba helyezzük át. A probléma állapotát itt tekintheti át:   XXX.

Köszönjük a cikkeinkhez   beküldött értékes hozzájárulását.
 
Szívélyes üdvözlettel:
