### ISSUE TITLE
Not sure yet,but I am trying to make everyrhing better.

### ISSUE THREAD

**Issue by sandor689** [MicrosoftDocs/azure-docs.hu-hu#41]
[Ide írja be a visszajelzését]

---
#### A dokumentum adatai

⚠ *Ezt a szakaszt ne szerkessze. A szakasz a docs.microsoft.com ➟ GitHub-problémák hivatkozásaihoz szükséges.*

* ID: 4459a0c8-0451-bbdf-3d2f-f62f46dc2240
* Version Independent ID: 7ebbbee6-1bd2-de5a-aabf-978d12099f3f
* Content: [A Windows 10 roaming beállítások referenciája](https://docs.microsoft.com/hu-hu/azure/active-directory/active-directory-windows-enterprise-state-roaming-windows-settings-reference)
* Content Source: [articles/active-directory/active-directory-windows-enterprise-state-roaming-windows-settings-reference.md](https://github.com/MicrosoftDocs/azure-docs.hu-hu/blob/live/articles/active-directory/active-directory-windows-enterprise-state-roaming-windows-settings-reference.md)
* Service: **active-directory**
* GitHub Login: @MarkusVi
* Microsoft Alias: **markvi**

**Comment by LisandroSu** [comment]
Hello, @sandor689 
 
Thanks once again for your comment.
Unfortunately, we are still missing information and we are unable to process your feedback. We are closing this GitHub issue at this time but we encourage you to submit more feedback in the future.

Kind regards,
Microsoft DOCS International Team
