### ISSUE TITLE
This page has been translated to hungarian by machine.

### ISSUE THREAD

**Issue by smil2k** [MicrosoftDocs/azure-docs.hu-hu#454]
The translation is very low quality. For example "spring" was translated to "rugo" which is the literal translation.

I was quite happy with the english pages, but I always get these low quality hungarian pages.

---
#### A dokumentum adatai

⚠ *Ezt a szakaszt ne szerkessze. A szakasz a docs.microsoft.com ➟ GitHub-problémák hivatkozásaihoz szükséges.*

* ID: c71343d5-5b28-5066-ec28-fafc4023aba3
* Version Independent ID: f5aaafd0-8961-2e5f-90eb-92fa16fa5828
* Content: [A Java Web Apps teljesítményének figyelése az Azure Application Insightsban](https://docs.microsoft.com/hu-hu/azure/azure-monitor/app/java-agent#feedback)
* Content Source: [articles/azure-monitor/app/java-agent.md](https://github.com/MicrosoftDocs/azure-docs.hu-hu/blob/master/articles/azure-monitor/app/java-agent.md)
* Service: **application-insights**
* GitHub Login: @mrbullwinkle
* Microsoft Alias: **mbullwin**

**Comment by srvbpigh** [comment]
Hello, @smil2k
 
Thank you for your feedback.
 
We are actively reviewing your comments and will get back to you soon.


Kind regards,
Microsoft DOCS International Team

**Comment by CeciAc** [comment]
Hello, @smil2k

Thank you for your feedback. The page in question has been machine-translated, which is not always perfectly understandable. We recently added a "Read in English" option on the right which allows you to switch to the English version without having to change the language settings.

Microsoft DOCS International Team
Kind regards,
