### ISSUE TITLE
Web Apps deploy problem

### ISSUE THREAD

**Issue by szmma** [MicrosoftDocs/azure-docs.hu-hu#455]
First of all, thank you for the tutorial . It was really helpful.
Secondly I got some problem on the last steps.  After I 
insert 'git push azure master'. on my consol . It wants me to authorise
myself. It won't accept my username/password . (fatal: Authentication failed for 'https://helloka.documents.azure.com:443/orders.git/'). I use my Microsoft user, and password.  What could I do to continue the process. Thank you!

---
#### A dokumentum adatai

⚠ *Ezt a szakaszt ne szerkessze. A szakasz a docs.microsoft.com ➟ GitHub-problémák hivatkozásaihoz szükséges.*

* ID: f7ad84a6-f6b6-dd21-e7be-865d922c7ad4
* Version Independent ID: 1f5a0315-d7b4-3f8f-3b1d-ae90c807859d
* Content: [Oktatóanyag: Node.js-webalkalmazás létrehozása a JavaScript SDK használatával az Azure Cosmos DB SQL API-adatok kezeléséhez](https://docs.microsoft.com/hu-hu/azure/cosmos-db/sql-api-nodejs-application#feedback)
* Content Source: [articles/cosmos-db/sql-api-nodejs-application.md](https://github.com/MicrosoftDocs/azure-docs.hu-hu/blob/master/articles/cosmos-db/sql-api-nodejs-application.md)
* Service: **cosmos-db**
* Sub-service: **cosmosdb-sql**
* GitHub Login: @SnehaGunda
* Microsoft Alias: **sngun**

**Comment by srvbpigh** [comment]
Hello, @szmma
 
Thank you for your feedback.
 
We are actively reviewing your comments and will get back to you soon.


Kind regards,
Microsoft DOCS International Team

**Comment by CeciAc** [comment]
Hello, @szmma

Your contribution is much appreciated. Our team can only answer feedback related to the documentation.
Please kindly log your product feedback by using the button "Give Product Feedback" at the bottom of the DOCS page.

If you have any feedback related to the documentation, please feel free to log it through this channel.
We truly appreciate your contribution to our articles. 
	
Kind regards,
Microsoft DOCS International Team
